name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/build-run-action@v2
    - uses: docker/build-push-action@v2


      
      
  
