name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Run the Docker image
      run: docker build -t ang-example .
           docker run -p 84:80  ang-example



      
      
  
